### ISSUE TITLE
Separate the force vector of Gravity into proper x and y coordinates.

### ISSUE THREAD

**Issue by magneticflux-** [BobsCandyCanes/Gravitation#1]
Check out [this](http://zonalandeducation.com/mstm/physics/mechanics/forces/forceComponents/forceComponents.html) for simple equations on separating the force vector. You assume a 45-45-90 triangle with the final force vector sqrt(2(f^2)), which is not the case 100% of the time. To find the angle from the center of the Planet to the center of the projectile, I suggest using the Math.atan2 method. You created a version of what it does in the AISandbox using several "if" statements.

**Comment by gcmvy3** [comment]
Thanks for the input. I didn't know about the atan2 method, that makes my life a whole lot easier.

Btw, all the code on here is really old. I'll try and update soon.

**Comment by magneticflux-** [comment]
You're welcome! When you get the most recent version uploaded, I'd like to see if I can learn anything about collision detection. I'm trying to get something basic rigged for my robot simulation.

**Comment by gcmvy3** [comment]
Alright, everything should be updated. 

As for collision detection, most of this is really simple bounding box collision. I just surround everything with its own Rectangle object and use Rectangle's "intersects" method to check if any of them collide.

If you want something a bit more complicated, I can send you the code for the Physics Simulator we're working on (it's in a private repository). It uses vertices and edges to allow for (almost) pixel-perfect collision detection.

**Comment by magneticflux-** [comment]
That sounds very interesting! I toyed with the idea of mathematically describing the shapes I wanted and checking the intersection point at various time values, but that seems a little out of reach. I'd love to see some of the code you have been working on. Daniel talked a little about it some time ago, but I hadn't heard news of it since.
